### ISSUE TITLE
Crash with odd carriage returns

### ISSUE THREAD

**Issue by matteosuppo** [arduino/arduino-builder#114]
This is a sketch with only CR as end-of-line markers (\r instead of \r\n)

[sketch_feb8a.zip](https://github.com/arduino/arduino-builder/files/121713/sketch_feb8a.zip)

The builder crashes with

```
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
arduino.cc/builder.(*PrototypesAdder).Run(0x732dd8, 0xc820012690, 0x0, 0x0)
	/home/msuppo/Work/arduino/arduino-builder/src/github.com/arduino/arduino-builder/src/arduino.cc/builder/prototypes_adder.go:78 +0x17da
arduino.cc/builder.(*ContainerAddPrototypes).Run(0x732dd8, 0xc820012690, 0x0, 0x0)
	/home/msuppo/Work/arduino/arduino-builder/src/github.com/arduino/arduino-builder/src/arduino.cc/builder/container_add_prototypes.go:56 +0x4f2
arduino.cc/builder.runCommands(0xc820012690, 0xc820311aa0, 0x1d, 0x1d, 0x1, 0x0, 0x0)
	/home/msuppo/Work/arduino/arduino-builder/src/github.com/arduino/arduino-builder/src/arduino.cc/builder/builder.go:187 +0x12b
arduino.cc/builder.(*Builder).Run(0xc820311c98, 0xc820012690, 0x0, 0x0)
	/home/msuppo/Work/arduino/arduino-builder/src/github.com/arduino/arduino-builder/src/arduino.cc/builder/builder.go:118 +0xe53
arduino.cc/builder.RunBuilder(0xc820012690, 0x0, 0x0)
	/home/msuppo/Work/arduino/arduino-builder/src/github.com/arduino/arduino-builder/src/arduino.cc/builder/builder.go:218 +0x39
main.main()
	/home/msuppo/Work/arduino/arduino-builder/src/github.com/arduino/arduino-builder/main.go:320 +0x2183
```

I debugged and discovered that the source code is not correctly divided into lines because of the CR, so it tries to split the source after it had ended, somehow :S

**Comment by facchinm** [comment]
Fixed by #115
