### ISSUE TITLE
Error caused by comment that starts with hash sign followed by space followed by number

### ISSUE THREAD

**Issue by per1234** [arduino/arduino-builder#233]
Using Arduino IDE 1.8.3 with Windows 7 64 bit

Demonstration sketch:
``` arduino
/*
# 1
*/
void setup() {
  test();
}
void loop() {}
void test() {}
```
Verbose output:
```
Arduino: 1.8.3 (Windows 7), Board: "Arduino/Genuino Uno"

E:\ArduinoIDE\arduino-1.8.3\arduino-builder -dump-prefs -logger=machine -hardware E:\ArduinoIDE\arduino-1.8.3\hardware -hardware C:\Users\per\AppData\Local\Arduino15\packages -hardware E:\Stuff\misc\electronics\arduino\hardware -tools E:\ArduinoIDE\arduino-1.8.3\tools-builder -tools E:\ArduinoIDE\arduino-1.8.3\hardware\tools\avr -tools C:\Users\per\AppData\Local\Arduino15\packages -built-in-libraries E:\ArduinoIDE\arduino-1.8.3\libraries -libraries E:\Stuff\misc\electronics\arduino\libraries -fqbn=arduino:avr:uno -ide-version=10803 -build-path C:\Users\per\AppData\Local\Temp\arduino_build_876900 -warnings=all -build-cache C:\Users\per\AppData\Local\Temp\arduino_cache_226063 -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.arduinoOTA.path=E:\ArduinoIDE\arduino-1.8.3\hardware\tools\avr -prefs=runtime.tools.avr-gcc.path=E:\ArduinoIDE\arduino-1.8.3\hardware\tools\avr -prefs=runtime.tools.avrdude.path=E:\ArduinoIDE\arduino-1.8.3\hardware\tools\avr -verbose E:\Stuff\misc\electronics\arduino\temp\issue\issue.ino
E:\ArduinoIDE\arduino-1.8.3\arduino-builder -compile -logger=machine -hardware E:\ArduinoIDE\arduino-1.8.3\hardware -hardware C:\Users\per\AppData\Local\Arduino15\packages -hardware E:\Stuff\misc\electronics\arduino\hardware -tools E:\ArduinoIDE\arduino-1.8.3\tools-builder -tools E:\ArduinoIDE\arduino-1.8.3\hardware\tools\avr -tools C:\Users\per\AppData\Local\Arduino15\packages -built-in-libraries E:\ArduinoIDE\arduino-1.8.3\libraries -libraries E:\Stuff\misc\electronics\arduino\libraries -fqbn=arduino:avr:uno -ide-version=10803 -build-path C:\Users\per\AppData\Local\Temp\arduino_build_876900 -warnings=all -build-cache C:\Users\per\AppData\Local\Temp\arduino_cache_226063 -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.arduinoOTA.path=E:\ArduinoIDE\arduino-1.8.3\hardware\tools\avr -prefs=runtime.tools.avr-gcc.path=E:\ArduinoIDE\arduino-1.8.3\hardware\tools\avr -prefs=runtime.tools.avrdude.path=E:\ArduinoIDE\arduino-1.8.3\hardware\tools\avr -verbose E:\Stuff\misc\electronics\arduino\temp\issue\issue.ino
Using board 'uno' from platform in folder: E:\ArduinoIDE\arduino-1.8.3\hardware\arduino\avr
Using core 'arduino' from platform in folder: E:\ArduinoIDE\arduino-1.8.3\hardware\arduino\avr
Detecting libraries used...
"E:\ArduinoIDE\arduino-1.8.3\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10803 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-IE:\ArduinoIDE\arduino-1.8.3\hardware\arduino\avr\cores\arduino" "-IE:\ArduinoIDE\arduino-1.8.3\hardware\arduino\avr\variants\standard" "C:\Users\per\AppData\Local\Temp\arduino_build_876900\sketch\issue.ino.cpp" -o "nul"
Generating function prototypes...
"E:\ArduinoIDE\arduino-1.8.3\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10803 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-IE:\ArduinoIDE\arduino-1.8.3\hardware\arduino\avr\cores\arduino" "-IE:\ArduinoIDE\arduino-1.8.3\hardware\arduino\avr\variants\standard" "C:\Users\per\AppData\Local\Temp\arduino_build_876900\sketch\issue.ino.cpp" -o "C:\Users\per\AppData\Local\Temp\arduino_build_876900\preproc\ctags_target_for_gcc_minus_e.cpp"
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x54ef00, 0x12200008)
	/home/jenkins/go/src/runtime/panic.go:500 +0x331
arduino.cc/builder.parseLineMarker(0x124d2d16, 0x3, 0x0, 0x0)
	/home/jenkins/workspace/arduino-builder-all-cross/src/arduino.cc/builder/filter_sketch_source.go:94 +0x178
arduino.cc/builder.(*FilterSketchSource).Run(0x125d00c8, 0x12260000, 0x0, 0x0)
	/home/jenkins/workspace/arduino-builder-all-cross/src/arduino.cc/builder/filter_sketch_source.go:57 +0x2d2
arduino.cc/builder.(*ContainerAddPrototypes).Run(0x614ef0, 0x12260000, 0x0, 0x0)
	/home/jenkins/workspace/arduino-builder-all-cross/src/arduino.cc/builder/container_add_prototypes.go:56 +0x3b8
arduino.cc/builder.runCommands(0x12260000, 0x1226fcc0, 0x22, 0x22, 0x1, 0x0, 0x0)
	/home/jenkins/workspace/arduino-builder-all-cross/src/arduino.cc/builder/builder.go:191 +0xe2
arduino.cc/builder.(*Builder).Run(0x1226fde4, 0x12260000, 0x0, 0x0)
	/home/jenkins/workspace/arduino-builder-all-cross/src/arduino.cc/builder/builder.go:124 +0x89f
arduino.cc/builder.RunBuilder(0x12260000, 0x0, 0x0)
	/home/jenkins/workspace/arduino-builder-all-cross/src/arduino.cc/builder/builder.go:222 +0x35
main.main()
	/home/jenkins/workspace/arduino-builder-all-cross/src/arduino.cc/arduino-builder/main.go:338 +0x1360
E:\ArduinoIDE\arduino-1.8.3\arduino-builder returned 2
Error compiling for board Arduino/Genuino Uno.
```

Output when run from command line with `-debug-level=10` option:
```
E:\ArduinoIDE\arduino-1.8.3\arduino-builder -compile -logger=machine -hardware E:\ArduinoIDE\arduino-1.8.3\hardware -hardware C:\Users\per\AppData\Local\Arduino15\packages -hardware E:\Stuff\misc\electronics\arduino\hardware -tools E:\ArduinoIDE\arduino-1.8.3\tools-builder -tools E:\ArduinoIDE\arduino-1.8.3\hardware\tools\avr -tools C:\Users\per\AppData\Local\Arduino15\packages -built-in-libraries E:\ArduinoIDE\arduino-1.8.3\libraries -libraries E:\Stuff\misc\electronics\arduino\libraries -fqbn=arduino:avr:uno -ide-version=10803 -build-path C:\Users\per\AppData\Local\Temp\arduino_build_876900 -warnings=all -build-cache C:\Users\per\AppData\Local\Temp\arduino_cache_226063 -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.arduinoOTA.path=E:\ArduinoIDE\arduino-1.8.3\hardware\tools\avr -prefs=runtime.tools.avr-gcc.path=E:\ArduinoIDE\arduino-1.8.3\hardware\tools\avr -prefs=runtime.tools.avrdude.path=E:\ArduinoIDE\arduino-1.8.3\hardware\tools\avr -verbose -debug-level=10 E:\Stuff\misc\electronics\arduino\temp\issue\issue.ino

===debug ||| Ts: {0} - Running: {1} ||| [1496966228 GenerateBuildPathIfMissing]
===info ||| Progress {0} ||| [0.00]
===debug ||| Ts: {0} - Running: {1} ||| [1496966228 EnsureBuildPathExists]
===info ||| Progress {0} ||| [2.94]
===debug ||| Ts: {0} - Running: {1} ||| [1496966228 ContainerSetupHardwareToolsLibsSketchAndProps]
===info ||| Progress {0} ||| [5.88]
===debug ||| Ts: {0} - Running: {1} ||| [1496966228 AddAdditionalEntriesToContext]
===debug ||| Ts: {0} - Running: {1} ||| [1496966228 FailIfBuildPathEqualsSketchPath]
===debug ||| Ts: {0} - Running: {1} ||| [1496966228 HardwareLoader]
===debug ||| Ts: {0} - Running: {1} ||| [1496966228 PlatformKeysRewriteLoader]
===debug ||| Ts: {0} - Running: {1} ||| [1496966228 RewriteHardwareKeys]
===debug ||| Ts: {0} - Running: {1} ||| [1496966228 ToolsLoader]
===debug ||| Ts: {0} - Running: {1} ||| [1496966235 TargetBoardResolver]
===info ||| Using board '{0}' from platform in folder: {1} ||| [uno E%3A%5CArduinoIDE%5Carduino-1.8.3%5Chardware%5Carduino%5Cavr]
===info ||| Using core '{0}' from platform in folder: {1} ||| [arduino E%3A%5CArduinoIDE%5Carduino-1.8.3%5Chardware%5Carduino%5Cavr]
===debug ||| Ts: {0} - Running: {1} ||| [1496966235 AddBuildBoardPropertyIfMissing]
===debug ||| Ts: {0} - Running: {1} ||| [1496966235 LibrariesLoader]
===debug ||| Ts: {0} - Running: {1} ||| [1496966235 SketchLoader]
===debug ||| Ts: {0} - Running: {1} ||| [1496966235 SetupBuildProperties]
===debug ||| Ts: {0} - Running: {1} ||| [1496966235 LoadVIDPIDSpecificProperties]
===debug ||| Ts: {0} - Running: {1} ||| [1496966235 SetCustomBuildProperties]
===debug ||| Ts: {0} - Running: {1} ||| [1496966235 AddMissingBuildPropertiesFromParentPlatformTxtFiles]
===debug ||| Ts: {0} - Running: {1} ||| [1496966235 ContainerBuildOptions]
===info ||| Progress {0} ||| [8.82]
===debug ||| Ts: {0} - Running: {1} ||| [1496966235 CreateBuildOptionsMap]
===debug ||| Ts: {0} - Running: {1} ||| [1496966235 LoadPreviousBuildOptionsMap]
===debug ||| Ts: {0} - Running: {1} ||| [1496966235 WipeoutBuildPathIfBuildOptionsChanged]
===debug ||| Ts: {0} - Running: {1} ||| [1496966235 StoreBuildOptionsMap]
===debug ||| Ts: {0} - Running: {1} ||| [1496966235 WarnAboutPlatformRewrites]
===info ||| Progress {0} ||| [11.76]
===debug ||| Ts: {0} - Running: {1} ||| [1496966235 RecipeByPrefixSuffixRunner]
===info ||| Progress {0} ||| [14.71]
===debug ||| Looking for recipes like {0}*{1} ||| [recipe.hooks.prebuild .pattern]
===debug ||| Ts: {0} - Running: {1} ||| [1496966235 ContainerMergeCopySketchFiles]
===info ||| Progress {0} ||| [17.65]
===debug ||| Ts: {0} - Running: {1} ||| [1496966235 SketchSourceMerger]
===debug ||| Ts: {0} - Running: {1} ||| [1496966235 SketchSaver]
===debug ||| Ts: {0} - Running: {1} ||| [1496966235 AdditionalSketchFilesCopier]
===debug ||| Ts: {0} - Running: {1} ||| [1496966235 loggerAction]
===info ||| Progress {0} ||| [20.59]
===info ||| Detecting libraries used... ||| []
===debug ||| Ts: {0} - Running: {1} ||| [1496966235 ContainerFindIncludes]
===info ||| Progress {0} ||| [23.53]
===debug ||| Ts: {0} - Running: {1} ||| [1496966235 GCCPreprocRunnerForDiscoveringIncludes]
"E:\ArduinoIDE\arduino-1.8.3\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10803 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-IE:\ArduinoIDE\arduino-1.8.3\hardware\arduino\avr\cores\arduino" "-IE:\ArduinoIDE\arduino-1.8.3\hardware\arduino\avr\variants\standard" "C:\Users\per\AppData\Local\Temp\arduino_build_876900\sketch\issue.ino.cpp" -o "nul"
===debug ||| Ts: {0} - Running: {1} ||| [1496966235 IncludesFinderWithRegExp]
===debug ||| Ts: {0} - Running: {1} ||| [1496966235 FailIfImportedLibraryIsWrong]
===debug ||| Ts: {0} - Running: {1} ||| [1496966235 WarnAboutArchIncompatibleLibraries]
===info ||| Progress {0} ||| [26.47]
===debug ||| Ts: {0} - Running: {1} ||| [1496966235 loggerAction]
===info ||| Progress {0} ||| [29.41]
===info ||| Generating function prototypes... ||| []
===debug ||| Ts: {0} - Running: {1} ||| [1496966235 ContainerAddPrototypes]
===info ||| Progress {0} ||| [32.35]
===debug ||| Ts: {0} - Running: {1} ||| [1496966235 GCCPreprocRunner]
"E:\ArduinoIDE\arduino-1.8.3\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10803 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-IE:\ArduinoIDE\arduino-1.8.3\hardware\arduino\avr\cores\arduino" "-IE:\ArduinoIDE\arduino-1.8.3\hardware\arduino\avr\variants\standard" "C:\Users\per\AppData\Local\Temp\arduino_build_876900\sketch\issue.ino.cpp" -o "C:\Users\per\AppData\Local\Temp\arduino_build_876900\preproc\ctags_target_for_gcc_minus_e.cpp"
===debug ||| Ts: {0} - Running: {1} ||| [1496966235 ReadFileAndStoreInContext]
===debug ||| Ts: {0} - Running: {1} ||| [1496966235 FilterSketchSource]
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x54ef00, 0x122d0008)
        /home/jenkins/go/src/runtime/panic.go:500 +0x331
arduino.cc/builder.parseLineMarker(0x12424cd6, 0x3, 0x0, 0x0)
        /home/jenkins/workspace/arduino-builder-all-cross/src/arduino.cc/builder/filter_sketch_source.go:94 +0x178
arduino.cc/builder.(*FilterSketchSource).Run(0x125d21b8, 0x122bc1e0, 0x0, 0x0)
        /home/jenkins/workspace/arduino-builder-all-cross/src/arduino.cc/builder/filter_sketch_source.go:57 +0x2d2
arduino.cc/builder.(*ContainerAddPrototypes).Run(0x614ef0, 0x122bc1e0, 0x0, 0x0)
        /home/jenkins/workspace/arduino-builder-all-cross/src/arduino.cc/builder/container_add_prototypes.go:56 +0x3b8
arduino.cc/builder.runCommands(0x122bc1e0, 0x124f7cc8, 0x22, 0x22, 0x1, 0x0, 0x0)
        /home/jenkins/workspace/arduino-builder-all-cross/src/arduino.cc/builder/builder.go:191 +0xe2
arduino.cc/builder.(*Builder).Run(0x124f7dec, 0x122bc1e0, 0x0, 0x0)
        /home/jenkins/workspace/arduino-builder-all-cross/src/arduino.cc/builder/builder.go:124 +0x89f
arduino.cc/builder.RunBuilder(0x122bc1e0, 0x0, 0x0)
        /home/jenkins/workspace/arduino-builder-all-cross/src/arduino.cc/builder/builder.go:222 +0x35
main.main()
        /home/jenkins/workspace/arduino-builder-all-cross/src/arduino.cc/arduino-builder/main.go:338 +0x1360
```

If the number is followed by a space then the above error does not appear but prototype generation does not occur:
```
Arduino: 1.8.3 (Windows 7), Board: "Arduino/Genuino Uno"

E:\ArduinoIDE\arduino-1.8.3\arduino-builder -dump-prefs -logger=machine -hardware E:\ArduinoIDE\arduino-1.8.3\hardware -hardware C:\Users\per\AppData\Local\Arduino15\packages -hardware E:\Stuff\misc\electronics\arduino\hardware -tools E:\ArduinoIDE\arduino-1.8.3\tools-builder -tools E:\ArduinoIDE\arduino-1.8.3\hardware\tools\avr -tools C:\Users\per\AppData\Local\Arduino15\packages -built-in-libraries E:\ArduinoIDE\arduino-1.8.3\libraries -libraries E:\Stuff\misc\electronics\arduino\libraries -fqbn=arduino:avr:uno -ide-version=10803 -build-path C:\Users\per\AppData\Local\Temp\arduino_build_876900 -warnings=all -build-cache C:\Users\per\AppData\Local\Temp\arduino_cache_226063 -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.arduinoOTA.path=E:\ArduinoIDE\arduino-1.8.3\hardware\tools\avr -prefs=runtime.tools.avr-gcc.path=E:\ArduinoIDE\arduino-1.8.3\hardware\tools\avr -prefs=runtime.tools.avrdude.path=E:\ArduinoIDE\arduino-1.8.3\hardware\tools\avr -verbose C:\Users\per\AppData\Local\Temp\arduino_modified_sketch_905580\issue.ino
E:\ArduinoIDE\arduino-1.8.3\arduino-builder -compile -logger=machine -hardware E:\ArduinoIDE\arduino-1.8.3\hardware -hardware C:\Users\per\AppData\Local\Arduino15\packages -hardware E:\Stuff\misc\electronics\arduino\hardware -tools E:\ArduinoIDE\arduino-1.8.3\tools-builder -tools E:\ArduinoIDE\arduino-1.8.3\hardware\tools\avr -tools C:\Users\per\AppData\Local\Arduino15\packages -built-in-libraries E:\ArduinoIDE\arduino-1.8.3\libraries -libraries E:\Stuff\misc\electronics\arduino\libraries -fqbn=arduino:avr:uno -ide-version=10803 -build-path C:\Users\per\AppData\Local\Temp\arduino_build_876900 -warnings=all -build-cache C:\Users\per\AppData\Local\Temp\arduino_cache_226063 -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.arduinoOTA.path=E:\ArduinoIDE\arduino-1.8.3\hardware\tools\avr -prefs=runtime.tools.avr-gcc.path=E:\ArduinoIDE\arduino-1.8.3\hardware\tools\avr -prefs=runtime.tools.avrdude.path=E:\ArduinoIDE\arduino-1.8.3\hardware\tools\avr -verbose C:\Users\per\AppData\Local\Temp\arduino_modified_sketch_905580\issue.ino
Using board 'uno' from platform in folder: E:\ArduinoIDE\arduino-1.8.3\hardware\arduino\avr
Using core 'arduino' from platform in folder: E:\ArduinoIDE\arduino-1.8.3\hardware\arduino\avr
Detecting libraries used...
"E:\ArduinoIDE\arduino-1.8.3\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10803 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-IE:\ArduinoIDE\arduino-1.8.3\hardware\arduino\avr\cores\arduino" "-IE:\ArduinoIDE\arduino-1.8.3\hardware\arduino\avr\variants\standard" "C:\Users\per\AppData\Local\Temp\arduino_build_876900\sketch\issue.ino.cpp" -o "nul"
Generating function prototypes...
"E:\ArduinoIDE\arduino-1.8.3\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10803 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-IE:\ArduinoIDE\arduino-1.8.3\hardware\arduino\avr\cores\arduino" "-IE:\ArduinoIDE\arduino-1.8.3\hardware\arduino\avr\variants\standard" "C:\Users\per\AppData\Local\Temp\arduino_build_876900\sketch\issue.ino.cpp" -o "C:\Users\per\AppData\Local\Temp\arduino_build_876900\preproc\ctags_target_for_gcc_minus_e.cpp"
"E:\ArduinoIDE\arduino-1.8.3\tools-builder\ctags\5.8-arduino11/ctags" -u --language-force=c++ -f - --c++-kinds=svpf --fields=KSTtzns --line-directives "C:\Users\per\AppData\Local\Temp\arduino_build_876900\preproc\ctags_target_for_gcc_minus_e.cpp"
Compiling sketch...
"E:\ArduinoIDE\arduino-1.8.3\hardware\tools\avr/bin/avr-g++" -c -g -Os -Wall -Wextra -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10803 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-IE:\ArduinoIDE\arduino-1.8.3\hardware\arduino\avr\cores\arduino" "-IE:\ArduinoIDE\arduino-1.8.3\hardware\arduino\avr\variants\standard" "C:\Users\per\AppData\Local\Temp\arduino_build_876900\sketch\issue.ino.cpp" -o "C:\Users\per\AppData\Local\Temp\arduino_build_876900\sketch\issue.ino.cpp.o"
C:\Users\per\AppData\Local\Temp\arduino_modified_sketch_905580\issue.ino: In function 'void setup()':

issue:12: error: 'test' was not declared in this scope

exit status 1
'test' was not declared in this scope
```

**Comment by facchinm** [comment]
Woah, thanks for reporting! It appears that the code triggers a bug when filtering sketch lines (by using `#line` directive) because the line partially matches that pattern. I'll take a look later today, thanks again
